### ISSUE TITLE
libssl -dev in Ubuntu 18.04

### ISSUE THREAD

**Issue by Dominique0804** [BaobabLims/baobab.lims#108] opened 2019-04-02 11:36 UTC
Problem with apt-get install zlib1g-dev libssl-dev libexpat1-dev libxslt1.1 libssl1.0-dev in **Ubuntu 18.04**

The following packages have unmet dependencies:
 libssl-dev : Conflicts: libssl1.0-dev but 1.0.2n-1ubuntu5.3 is to be installed
 libssl1.0-dev : Conflicts: libssl-dev but 1.1.0g-2ubuntu4.3 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Dominique0804** [comment] 2019-07-26 11:24
**Installation for Ubuntu 18.04 ONLY**

**Plone dependencies**
Plone framework requires the installation of additional system packages. Without those packages available in your system Plone will not compile.

    sudo apt install -y python2.7 python-pip build-essential gcc python-dev git-core libffi-dev libpcre3 libpcre3-dev autoconf libtool pkg-config zlib1g-dev libssl-dev libexpat1-dev libxslt1.1 gnuplot libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libxml2-dev libxslt1-dev

**Download Plone 4.3 Unified Installer**
The product Baobab LIMS is implemented and tested with Plone 4.3.11, a version released in 2016-09-12. You can download Plone 4.3.x by visiting the Plone site. Select and click on the Unified installer of your choice or use wget command line in your terminal with the path to the Plone version to install. Only Plone 4.3.11 can be used. Version 5 is available but will not work.

    wget --no-check-certificate https://launchpad.net/plone/4.3/4.3.11/+download/Plone-4.3.11-r1-UnifiedInstaller.tgz
 
Depending in the option used for the download, the installer would be in the *~/Downloads* directory if the download has been done from the Plone site. If the second option rather used i.e, the wget command line, the installer should be downloaded into the current directory.

**Install Plone**
To continue the installation, in your terminal change directory into the folder containing the downloaded file then run the following command line to unpack the archive file.

    tar -xf Plone-4.3.11-r1-UnifiedInstaller.tgz
Change to the extracted folder cd Plone-4.3.11-r1-UnifiedInstaller in your terminal, and run this next command to install Plone

    ./install.sh --target=/usr/local/Plone --with-python=$(which python2.7) zeo
where --target is the parameter used to specify the path to the installation folder, --with-python to add and build Python package from your system (python 2.7),  and finally zeo is the option to install Plone as a Client-Server application. Plone requires Python2.7 to work. Run *./install.sh --help* to get the full list of the available parameters and their meaning.

> Note: In production mode, prepend the the previous command line with sudo then run.

**Install Baobab LIMS**
In the new folder created /usr/local/Plone exists another folder named zeocluster. This folder contains *buildout.cfg* configuration file. Find in the configuration file, the section starting with eggs=, and add baobab.lims and bika.lims to the existing entries. Bika LIMS is a dependency that Baobab LIMS needs to function. Some of modules in Baobab LIMS reference modules in Bika LIMS.

    eggs =
        Plone
        Pillow
        bika.lims
        baobab.lims
        graphite.theme
Add to the section develop = the path to your version of Baobab LIMS and BIKA LIMS that should be already downloaded into your local machine. By convention it is preferable to put the source code in zeocluster/src of your Plone installation folder.

    develop =
        src/bika.lims
        src/baobab.lims
        src/graphite.theme     
Add the following line to the buildout file. add it in the buildout section: index = https://pypi.python.org/simple/ because of the below warning.

> Warning

> If you encounter the packages not found issue, add the following line, issue related to this: https://github.com/BaobabLims/baobab.lims/issues/55

 In the [buildout] section add the below line.

    index = https://pypi.python.org/simple/
    
 It will also be useful to add the following lines to the bottom of the buildout.cfg file:

    Products.AdvancedQuery = 3.0.4
    cairocffi = 0.9.0

**Save the file**

Check out the bika, baobab and graphite code bases from GitHub
Use git clone or fork this project to have your own copy in your local machine. For developers, any change in your source code that you judge interesting and useful for the community please create a Pull request to us and let us know if you want to become a collaborator in the Baobab LIMS project.

 Change directory into zeocluster/src and run the git clone command from there.


    cd src
    sudo git clone https://github.com/BaobabLims/bika.lims.git
    sudo git clone https://github.com/BaobabLims/baobab.lims.git
    sudo git clone https://github.com/BaobabLims/graphite.theme.git
    sudo chown -R plone_buildout:plone_group /usr/local/Plone

[Links] below

(https://github.com/BaobabLims/bika.lims.git)
(https://github.com/BaobabLims/baobab.lims.git)
(https://github.com/BaobabLims/graphite.theme.git)

###Additional packages will need to be added

    cd /usr/local/Plone/Python2.7
    sudo wget https://bootstrap.pypa.io/get-pip.py
    sudo bin/python get-pip.py
    sudo bin/python -m pip install xlsxwriter

Exit out of the src directory and back into the zeocluster directory and run the bin/buildout command. Buildout will download and install all the declared dependencies.

     cd ..
     bin/buildout
     
If you installed Plone as a root user i.e., using sudo, you should run the buildout command line with the user plone_buildout, this user is automatically created during the Plone installation:

     sudo -u plone_buildout bin/buildout
     
**Test your installation**
First, you will need to start the zeoserver (this is the database process).

     bin/zeoserver start

**To start a Plone client in debug mode, run this command:**

     bin/client1 fg
If you installed Plone as a root user, you will need to use the following commands instead:

     sudo -u plone_daemon bin/zeoserver start
     sudo -u plone_daemon bin/client1 fg
     
> Note any error messages, and take corrective action if required. If no errors are encountered, you can press Control+C to exit.

In your preferred browser, firefox or google chrome, run http://localhost:8080/ and start working with Baobab LIMS. Enjoy it!

In production mode, other important tools need to be installed and configured, like Supervisorctl and nginx. The following article details the process to follow to add those tools cited before.

**Comment by Dominique0804** [comment] 2019-08-20 09:11
**Note: **  Please ensure that you have the correct permissions for the installation folder. Running this command will provide full permissions for the installation

   sudo chmod -R 777 /usr/local/Plone

**Comment by zipho** [comment] 2020-05-05 18:41
So this is resolve. Will close it accordingly

**Closed by zipho** 2020-05-05 18:41 UTC

**Comment by alinaili** [comment] 2021-08-25 13:09
Error while installing Baobab LIms
Error: Couldn't find a distribution for 'collective.wtf'.
[error_Installation_BaobabLims.txt](https://github.com/BaobabLims/baobab.lims/files/7047165/error_Installation_BaobabLims.txt)
PLone buildout and worked correctly when you delete all source file from src folder.
the problem is not related with ubuntu system.

**Comment by alinaili** [comment] 2021-09-22 11:31
Several packages are not installed automatically in the **eggs folder of buildout-cache** like "collective.wtf
When you add manually the List of packages for eggs folder, any errors appeared in the buildout.

**Comment by shunido** [comment] 2023-01-18 16:08
Anyone made it work on ubuntu 22.04 ??
